# Generated by Django 4.0.3 on 2022-04-10 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_tasks_players'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='players',
            new_name='player',
        ),
    ]
