# Generated by Django 3.2.8 on 2022-04-10 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_players_players_player'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Players',
            new_name='Tasks',
        ),
    ]
