# Generated by Django 3.2.8 on 2022-04-10 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_rename_players_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='player',
            new_name='task',
        ),
    ]
